apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ticketflow-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticketflow-app
  minReplicas: 1
  maxReplicas: 5 
  targetCPUUtilizationPercentage: 10